# Region: WayPoint
"4": "ReceptionDesk"
"5": "ReceptionKitchen"
"1": "HospActRec2"
"2": "HospActRec3"
"7": "Station1"
"8": "HospActRec1"
"13": "CorpActRec3"
"18": "SuppActRec1"
"15": "KitchenActRec2"
"17": "KitchenTableLow"
"16": "KitchenCounter1"
"20": "NewArea3"
"19": "NewArea3"

# "134": ["KitchenTableLow", "KitchenTableHigh"]
